sudo: required
services:
  - docker

before_install:
 - docker build -t harpreetbrar1/knowledgebase2 -f Dockerfile.dev .

script:
  - docker run -e CI=true harpreetbrar1/knowledgebase2 npm run test

deploy:
  - provider: elasticbeanstalk
  - access_key_id: "AKIATTIO7ZPOWYVM47QT"
  - secret_access_key:
      secure: "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" 
  - region: "us-west-2"
  - app: "knowledgebase"
  - env: "Knowledgebase-env"
  - bucket_name: "elasticbeanstalk-us-west-2-247528934365"
