sudo: required
services:
  - docker

before_install:
 - docker build -t harpreetbrar1/knowledgebase2 -f Dockerfile.dev .

script:
  - docker run -e CI=true harpreetbrar1/knowledgebase2 npm run test

deploy:
  - provider: elasticbeanstalk
  - edge: true
  - access_key_id: $ACCESS
  - secret_access_key:
      secure: "$SECRET"
  - region: "us-west-2"
  - app: "knowledgebase"
  - env: "Knowledgebase-env"
  - bucket_name: "elasticbeanstalk-us-west-2-247528934365"